def test_func():
    # x = 10 / 0
    raise ZeroDivisionError()


# test_func()
# exception_obj = Exception()
# error_object = ZeroDivisionError()
# print("> ", Exception)
# print(">> ", exception_obj)
# print(">>> ", error_object)

# raise Exception()
test_func()